### ISSUE TITLE
How to catch ECONNREFUSED?

### ISSUE THREAD

**Issue by lukasz-wronski** [sparkida/ftpimp#10]
I'm walking the FTP to list files and folders. I started connection with ftp.connect, and then after making more or less ftp.ls operations I'm getting unhandled error ECONNREFUSED. What can I do to handle this error?

**Comment by sparkida** [comment]
hmm sounds like a bug...that usually happens when a request is being made before another request has finished. FTPimp generally manages things well enough to keep this from ever happening.

To answer the question you can usually [catch uncaughtException](https://nodejs.org/api/process.html#process_event_uncaughtexception) with 
```
process.on('uncaughtExcepion', function (error) { ...
```

So I could investigator the source of the issue better, could you past the code you are running to generate that error?

**Comment by lukasz-wronski** [comment]
Thanks for quick response. You can check my sources here: https://github.com/lukasz-wronski/vscode-ftp-sync/tree/0.2.0. Error usually happen on /modules/syncHelper.js in listRemoteFiles method.

**Comment by sparkida** [comment]
awesome
